#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_INIT)  += init

init: common libsel4 libmuslc libsel4allocman libsel4vka \
		libsel4platsupport libsel4muslcsys libsel4utils \
		libcpio libelf libplayground libdatastruct libsel4simple \
		libsel4vspace libsel4utils libutils libsel4vspace
