#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_INIT)  	+= init

init: 	common libsel4 libmuslc libsel4vka libcpio libelf libsel4allocman libsel4platsupport libplatsupport libplaygroundsys libplayground libsel4simple libsel4simple-default libsel4vspace libsel4utils libutils libcpio libelf
